### ISSUE TITLE
Focus does not work correctly

### ISSUE THREAD

**Issue by rsaccon** [qu1x/kiss3d-trackball#1]
I like your trackball implementation very much and have started to integrate it into one of my projects. However the focus functionality seems not to work properly for me. 

I am using a mouse on a mac, and have a simple kiss3d based demo app using exactly the trackball code from this repo. Here is what happens:

I click near the origin -> the origin moves away in the opposite direction (but correct distance)
I click again at same place -> the origin moves further away (again opposite direction but correct distance)
...
... until origin is outside viewport 

Am I doing something wrong or is there anything wrong with `Trackball.frame.local_slide` ?

**Comment by n3vu0r** [comment]
Glad you like this implementation!

I think what you describe is actually intended. At least, it makes sense when the use case is to inspect objects. I'm using this trackball implementation at the moment to inspect multiple objects close to each other. The idea of the focus operation is following: If you click at an object (for example near the origin), this object (the click position) is supposed to jump to the center of the viewport. If you then don't move your mouse and click again, that click position (another object or empty space between objects) will be centered, effectively moving the first object further in its direction until it leaves the viewport.

What is your use case or expected behavior?

**Comment by rsaccon** [comment]
OMG, yes, this makes perfect sense. Thanks a lot for the explanation. I somehow assumed, where I click, the origin has to move to that screen position. But now I see, that makes no sense.

My use case is Camera / viewport navigation for a 3d nurbs modeling experiment based on [truck CAD kernel](https://github.com/ricosjp/truck). I have also some other little problems and questions, will open separate issue.

**Comment by n3vu0r** [comment]
> My use case is Camera / viewport navigation for a 3d nurbs modeling experiment based on [truck CAD kernel](https://github.com/ricosjp/truck).

Looks interesting, starred it.

> I have also some other little problems and questions, will open separate issue.

Happy to help.
